name: Release for Duende.IdentityServer.Admin FMFX fork - UI and BusinessLogic
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version in the format: MAJOR.MINOR.PATCH[-PRERELEASE]'
        required: true

defaults:
  run:
    working-directory: src

jobs:
  release:

    runs-on: windows-latest

    steps:

    - name: Allow longpaths
      run: gh config --system core.longpaths true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Get release version
      run: |
          $version = '${{ github.event.inputs.version }}'
          echo "Release version: $version"
          echo "RELEASE_VERSION=$version" >> $Env:GITHUB_ENV

    - name: Build
      run: |
          dotnet nuget add source https://nuget.pkg.github.com/FreemarketFX/index.json --name GitHub-FreemarketFX --username PersonalAccessToken --password ${{ secrets.ADMIN_READ_NUGET_TOKEN }} --store-password-in-clear-text
          dotnet pack Skoruba.Duende.IdentityServer.Admin.UI\Skoruba.Duende.IdentityServer.Admin.UI.csproj --configuration Release /p:Version=$Env:RELEASE_VERSION
          dotnet pack Skoruba.Duende.IdentityServer.Admin.BusinessLogic\Skoruba.Duende.IdentityServer.Admin.BusinessLogic.csproj --configuration Release /p:Version=$Env:RELEASE_VERSION
          dotnet pack Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Identity\Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Identity.csproj --configuration Release /p:Version=$Env:RELEASE_VERSION

    - name: Push artifacts
      run: |
           dotnet nuget push ..\artifacts\*.nupkg --source https://nuget.pkg.github.com/FreemarketFX/index.json --api-key ${{ secrets.ADMIN_PUBLISH_NUGET_TOKEN }} --skip-duplicate