name: Release for Duende.IdentityServer.Admin FMFX fork - UI and BusinessLogic
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version in the format: MAJOR.MINOR.PATCH[-PRERELEASE]'
        required: true

defaults:
  run:
    working-directory: src

jobs:
  Build_Release:

    runs-on: windows-latest

    steps:
    - name: Longpaths
      run: git config --system core.longpaths true
      working-directory: /

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Get release version
      run: |
          $version = '${{ github.event.inputs.version }}'
          echo "Release version: $version"
          echo "RELEASE_VERSION=$version" >> $Env:GITHUB_ENV

    - name: Build
      run: |
          dotnet nuget add source https://nuget.pkg.github.com/FreemarketFX/index.json --name GitHub-FreemarketFX --username PersonalAccessToken --password ${{ secrets.ADMIN_READ_NUGET_TOKEN }} --store-password-in-clear-text
          dotnet pack Skoruba.Duende.IdentityServer.Admin.UI\Skoruba.Duende.IdentityServer.Admin.UI.csproj --configuration Release /p:Version=$Env:RELEASE_VERSION
          dotnet pack Skoruba.Duende.IdentityServer.Admin.BusinessLogic\Skoruba.Duende.IdentityServer.Admin.BusinessLogic.csproj --configuration Release /p:Version=$Env:RELEASE_VERSION
          dotnet pack Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Identity\Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Identity.csproj --configuration Release /p:Version=$Env:RELEASE_VERSION

    - name: Push artifacts
      run: |
           dotnet nuget push D:\a\Duende.IdentityServer.Admin\Duende.IdentityServer.Admin\src\Skoruba.Duende.IdentityServer.Admin.UI\bin\Release\Skoruba.Duende.IdentityServer.Admin.UI.*.nupkg --source https://nuget.pkg.github.com/FreemarketFX/index.json --api-key ${{ secrets.ADMIN_PUBLISH_NUGET_TOKEN }} --skip-duplicate
           dotnet nuget push D:\a\Duende.IdentityServer.Admin\Duende.IdentityServer.Admin\src\Skoruba.Duende.IdentityServer.Admin.BusinessLogic\bin\Release\Skoruba.Duende.IdentityServer.Admin.BusinessLogic.*.nupkg --source https://nuget.pkg.github.com/FreemarketFX/index.json --api-key ${{ secrets.ADMIN_PUBLISH_NUGET_TOKEN }} --skip-duplicate
           dotnet nuget push D:\a\Duende.IdentityServer.Admin\Duende.IdentityServer.Admin\src\Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Identity\bin\Release\Skoruba.Duende.IdentityServer.Admin.BusinessLogic.Identity.*.nupkg --source https://nuget.pkg.github.com/FreemarketFX/index.json --api-key ${{ secrets.ADMIN_PUBLISH_NUGET_TOKEN }} --skip-duplicate